spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          # En docker debe ser http://oauth-server:9000
          # En local sin docker puede ser http://localhost:9000
          issuer-uri: ${OAUTH_ISSUER_URI:http://localhost:9000}

  cloud:
    gateway:
      default-filters:
        # Reenvía el header Authorization: Bearer ... hacia los microservicios
        - TokenRelay

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns:
              - "http://localhost:*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - Accept
              - Origin
              - X-Requested-With
            exposedHeaders:
              - Authorization
            # Para Opción A (Bearer Token), lo recomendado es NO usar cookies:
            allowCredentials: false
            maxAge: 3600

      routes:
        - id: c-catalogo
          uri: ${CATALOGO_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/catalogo/**

        - id: c-inventario
          uri: ${INVENTARIO_SERVICE_URI:http://localhost:8082}
          predicates:
            - Path=/api/inventario/**

        - id: c-ventas
          uri: ${VENTAS_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/api/ventas/**

        - id: c-reportes
          uri: ${VENTAS_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=/api/reportes/**

server:
  port: 8085

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
