server:
  port: 8084

spring:
  application:
    name: ms-usuarios

  datasource:
    url: jdbc:postgresql://localhost:5432/usuariosdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
