services:
  backend-cadena-farmacias-ms-gw:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-cadena-farmacias-ms-gw
    ports:
      - "8085:8085"
    networks:
      - red_cadena_farmacia
    environment:
      CATALOGO_SERVICE_URI: http://localhost:8081
      INVENTARIO_SERVICE_URI: http://localhost:8082
      VENTAS_SERVICE_URI: http://localhost:8083

      # Opción A: Gateway como Resource Server (valida JWT)
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:9000

      # Recomendado para depurar si está protegiendo o no
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG

networks:
  red_cadena_farmacia:
    driver: bridge
